const loveNotes = [
    "Sen hayatımda başıma gelen en güzel şeysin. ✨",
    "Gülüşün, dünyadaki tüm karanlıkları aydınlatmaya yeter. 💖",
    "Seninle geçirdiğim her saniye, ömrüme ömür katıyor. ⏳",
    "Dünyadaki en güvenli limanım senin kolların. ⚓",
    "Gözlerine her baktığımda, geleceğimi orada görüyorum. 👀",
    "Kalbinin güzelliği yüzüne öyle bir yansımış ki... 😍",
    "Seni sevmek, nefes almak kadar doğal ve zorunlu benim için. 💨",
    "Her sabah senin varlığınla uyanmak en büyük şükür sebebim. 🙏",
    "Seninleyken zamanın nasıl geçtiğini hiç anlamıyorum. 🕰️",
    "Ruhumun eşi, kalbimin tek sahibi sensin. 💍",
    "Seninle yaşlanmak, hayallerimin en tepesinde. 👵👴",
    "Elini tuttuğumda dünyayı fethedecekmişim gibi hissediyorum. 🌍",
    "Sesin, duyduğum en güzel melodi. 🎶",
    "Varlığın, hayatımın en değerli hediyesi. 🎁",
    "Seninle sıradan bir an bile, ömürlük bir anıya dönüşüyor. 📸",
    "Aşkın, damarlarımda akan en saf enerji. ⚡",
    "Sen benim evimsin; nerede olursak olalım, senin yanın huzur. 🏠",
    "Her düştüğümde beni kaldıran o sıcacık ellerini hiç bırakma. 🤝",
    "Seninle hayaller kurmak bile, onları yaşamış kadar güzel. 💭",
    "Ayşe, senin adın kalbimde sonsuz bir mührün adı. ❤️",
    "Güneş batsa da, senin parlaklığın benim yolumu aydınlatır. 🌟",
    "En zor günlerimde, senin bir tek bakışın her şeyi unutturuyor. 😊",
    "Seninle paylaştığımız sustuğumuz anlar bile çok değerli. 🤫",
    "Beni ben yapan her şeyin içinde biraz da sen varsın. 🧩",
    "Dünyayı bir kenara bıraktığım, sadece senin olduğun o yer çok güzel. 🪐",
    "Aklımda hep sen, kalbimde hep senin sevgin... 🧠❤️",
    "Seni her gün yeniden seviyorum, sanki ilk defaymış gibi. ✨",
    "Yıldızlar kadar uzaktaydın belki başlangıçta, şimdi nefesim kadar yakınımdasın. ✨",
    "Seninle kavga etmeyi bile, başkasıyla gülmeye değişmem. 😤❤️",
    "Mutfaktaki dağınıklığını bile seviyorum, senin her halin özel. 🍳",
    "Uykulu halindeki o masumiyetin, dünyadaki en tatlı şey. 😴",
    "Seninle bir kahve içmek, en lüks tatilden daha keyifli. ☕",
    "Şarkılar senin adını sayıklıyor sanki, her nakarat seni anlatıyor. 🎵",
    "Bana aşkı öğreten, sevmeyi sevdiren kadın... 👩‍🏫❤️",
    "Seninle paylaştığımız her an, bir film karesi kadar estetik. 🎞️",
    "Kalbimdeki her atış, sadece senin ismini zikrediyor: Ayşe... Ayşe... 🥁",
    "Sonsuzluk bir kavram değil, seninle geçecek ömrün adı benim için. ♾️",
    "Baharda açan ilk çiçek gibisin; taze, narin ve büyüleyici. 🌸",
    "Kışın en soğuk gününde, senin varlığın içimi ısıtan tek soba. 🔥",
    "Fırtınalara karşı durduğum o dev kale sensin. 🏰",
    "Seninle dertleşmek, dünyanın en iyi terapisinden daha etkili. 🗣️❤️",
    "Nazını, niyazını, her bir mimiğini ezbere biliyorum ve hepsine bayılıyorum. 🥰",
    "Güneşimsin; gündüzümü aydınlatan, ruhumu ısıtan... 🌞",
    "Ayımsın; gecemi parlatan, rüyalarımı süsleyen... 🌙",
    "Senin mutluluğun, benim hayattaki tek misyonum. 🎯",
    "Gözyaşlarının tek bir damlası için dünyayı yakarım, unutma. 🔥💧",
    "Birlikte yapacağımız o kadar çok şey var ki, heyecandan kalbim duracak. 🎢",
    "Hayat kumarında kazandığım en büyük ikramiye sensin. 🎰💰",
    "Seni anlatmaya kelimeler yetmez; sessizliğimdeki en büyük çığlıksın. 🤫🔊",
    "Mert, senin sevginle her gün yeniden doğuyor sevgilim. 🏁🏎️"
];

function triggerJar() {
    const noteText = document.getElementById('jar-note-text');
    const randomNote = loveNotes[Math.floor(Math.random() * loveNotes.length)];
    noteText.innerText = randomNote;
    document.getElementById('memoryJarModal').style.display = 'flex';
}
